### PR TITLE
US_2-02

### PR DESCRIPTION
**Pull request by joaofpereira**
This **PR** adds the following features, regarding **US 2-02**:
- Sorting Centers can now list their incoming resources
- Sorting Centers can now delete an incoming resource (this is implemented but when the transportation starts, Sorting Centers can no longer delete it)

### CODE REVIEW

**Comment by ferrolho** [comment]
I have thoroughly reviewed the code and it seems to me that everything is as it should be. :+1: 
I have also monkey tested the features introduced by this US, and again everything seems to do what it is supposed to do.

For that reason, I approve the merge of this PR into _master_.

**Comment by lycantropus** [comment]
I looked at the code and it seems fine.
Monkey tested the new features of the US, everything is ok.
I dont particularly like the menus to access the sorting center options (i think we should see another alternative, if there is, or simply give it a greater fade time).
Also, there is a bug in the form used to post a new supply when you resize the window (the type of resource cell is not going under the other cells).

i can approve the merge, **but we must fix later the display bug on resize.**

**Comment by lycantropus** [comment]
There should be no visual bug after the resize now with the new commit.

**Comment by joaofpereira** [comment]
Thank for both your reviews. We should talk about navbar style/animation during the next class.
Thank you @lycantropus for noticing and solving the presentation bug. :+1: 

Going to merge this into master now.

**Pull request merged**
