### PR TITLE
US_1-01

### PR DESCRIPTION
**Pull request by ferrolho**
To dev team: please review this US, and if everything is ok confirm the PR (Pull Request).

### CODE REVIEW

**Comment by joaoBordalo** [comment]
To me, I aprove ! OK

**Comment by ferrolho** [comment]
Thank you for the revision @joaoBordalo. :+1: 
As soon as one more person reviews the changes, I will merge this PR to master. :smiley:

**Comment by Rafikii** [comment]
Done. OK

**Comment by ferrolho** [comment]
Thank you @Rafikii :smiley: 
Since two people have already positively reviewed the Pull Request, I will proceed to merge it into master.

**Important for future PRs:**
Each PR should be positively reviewed by **at least** two people! Only then can the Developer who created the PR merge it into master.

**Comment by ferrolho** [comment]
Ups... accidentally closed the PR. Nothing to worry about!
Going to merge this now! :+1:

**Comment by joaofpereira** [comment]
This looks very nice so I approve this PR. :dart:

**Pull request merged**
